<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['firewall_custom_app_description'] = 'Aplikacja niestandardowych reguł Firewalla dostarcza nisko poziomowego narzędzia do konfiguracji zaawansowanych reguł zapory sieciowej.';
$lang['firewall_custom_app_name'] = 'Niestandardowe reguły Firewall';
$lang['firewall_custom_command_is_not_permitted'] = 'Polecenie nie jest dozwolone.';
$lang['firewall_custom_description_invalid'] = 'Opis jest nieprawidłowy.';
$lang['firewall_custom_firewall_rule_invalid'] = 'Reguła firewalla jest nieprawidłowa.';
$lang['firewall_custom_help_dragging'] = 'Kolejność niestandardowych reguł firewalla jest istotna  - kliknij i przeciągnij regułę w tabeli w górę lub do dołu aby zmienić jej kolejność.';
$lang['firewall_custom_restart_required'] = 'Kolejność reguł mogła zostać zmieniona - firewall musi zostać ponownie uruchomiony.';
$lang['firewall_custom_summary'] = 'Pozwala na dodawanie niestandardowych reguł do firewalla.  W zaawansowanych lub mocno dostosowanych środowiskach sieciowych, dodatkowe reguły firewalla, które nie mogą zostać dodane używając dostępnych aplikacji zapory sieciowej (Przychodzące, DMZ, MultiWAN, Przekierowywanie portów, itd) do uzyskania wymaganych zabezpieczeń i trasowania pakietów mogą zostać osiągnięte korzystając z aplikacji niestandardowych reguł firewalla.  Korzystać z tego modułu powinni jedynie zaawansowani użytkownicy.';
